# Generated by Django 3.0.5 on 2020-04-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0003_remove_hotel_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='Image',
        ),
    ]
